# Generated by Django 5.2.10 on 2026-02-01 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_swaprequest_owner_agreed_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, help_text='Specific area/street (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('north', 'North Delhi'), ('south', 'South Delhi'), ('east', 'East Delhi'), ('west', 'West Delhi'), ('central', 'Central Delhi'), ('ne', 'North-East Delhi'), ('nw', 'North-West Delhi'), ('se', 'South-East Delhi'), ('sw', 'South-West Delhi')], default='central', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', '📱 Electronics & Tech'), ('fashion', '👕 Fashion & Accessories'), ('home', '🏠 Home & Furniture'), ('fitness', '🏋️ Fitness & Sports'), ('books', '📚 Books & Media'), ('toys', '🎮 Toys & Games'), ('other', '✨ Other Items')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'location'], name='exchange_it_categor_a7cf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='exchange_it_created_f6ed34_idx'),
        ),
    ]
